services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_DB: SST-Internal_Tools
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "3338:5432"

